definitions:
  controllers.UserAddReq:
    properties:
      Age:
        type: integer
      Name:
        type: string
    required:
    - Name
    type: object
  controllers.UserQueryReq:
    properties:
      Name:
        type: string
    required:
    - Name
    type: object
info:
  contact: {}
paths:
  /Car:
    post:
      consumes:
      - application/json
      description: Add car with Model
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.UserQueryReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Add car
      tags:
      - Car
  /User:
    get:
      consumes:
      - application/json
      description: User search
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.UserQueryReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: User search
      tags:
      - User
    post:
      consumes:
      - application/json
      description: add User
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.UserAddReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: add User
      tags:
      - User
swagger: "2.0"
